#! /usr/bin/python

import sys
import os
import datetime
import time
import commands

def waitCheck(status):
  return os.WIFEXITED(status) and os.WEXITSTATUS(status) == 0

if len(sys.argv) == 1:
  name = os.getcwd().replace("/", "_")[1:]
  tarSubjects = "."
else:
  name = ""
  tarSubjects = ""
  for i in range(1, len(sys.argv)):
    curr = sys.argv[i]
    if not curr.startswith("/"):
      curr = os.getcwd() + "/" + curr
    curr = curr[1:].replace("//", "/").replace("/", "_")
    if i > 1:
      name += ","
      tarSubjects += " "
    name += curr
    tarSubjects += "'" + sys.argv[i] + "'"

home = os.path.expandvars("$HOME")
backupDir = "/".join([home, "backups", name])

if not os.path.isdir(backupDir):
  if os.path.exists(backupDir):
    raise Exception("%s is not a directory" % backupDir)
  else:
    os.makedirs(backupDir)

now = str(datetime.datetime.fromtimestamp(time.time())).replace(' ', 'T')

tarball = "%s/%s.tgz" % (backupDir, now)
cmd = "tar --exclude stddbDart.tar.gz -czf %s %s" % (tarball, tarSubjects)
(status, output) = commands.getstatusoutput(cmd)
if waitCheck(status):
  print output
  (status, output) = commands.getstatusoutput("ls -hl %s" % tarball)
  print output
else:
  print >> sys.stderr, "%s failed: %s" (cmd, output)
  raise Exception("tar command failed")
