#! /usr/bin/python

import sys
import getopt

def toLeft(s, width):
  return s.ljust(width)

def toRight(s, width):
  return s.rjust(width)

def toCenter(s, width):
  return s.center(width)

def process(lines):
  maxWidth = max([len(line) for line in lines])
  print fillChar * (maxWidth+4)
  for line in lines:
    print "%s %s %s" % (fillChar, just(line, maxWidth), fillChar)
  print fillChar * (maxWidth+4)

just = toLeft
fillChar = '#'

(opts, args) = getopt.getopt(sys.argv[1:], "c:", ["character=", "left", "center", "right"])
for (opt,arg) in opts:
  if opt == "--left":
    just = toLeft
  elif opt == "--right":
    just = toRight
  elif opt == "--center":
    just = toCenter
  elif opt in ["-c", "--character"]:
    fillChar = arg[0]

assert args or (not sys.stdin.isatty()), "Syntax: banner [message]"

if args:
  process([' '.join(args)])
else:
  process(sys.stdin.read().strip('\n').split('\n')) 
