#! /usr/bin/python

import os
import sys
import os.path

verbose = False
hits = 0

def process(path):
  global hits

  ret = False

  path = path % os.environ
  if os.path.isfile(path):
    if verbose:
      print "You%s have %s" % (" also" if hits else "", path)
    else:
      print path
      ret = True
    hits += 1
  elif verbose:
    print "You do not have %s" % path

  return ret

#  ~/.bash_profile, ~/.bash_login, and ~/.profile,

verbose = ("-v" in sys.argv) or ("--verbose" in sys.argv)

if not process("%(HOME)s/.bash_profile"):
  if not process("%(HOME)s/.bash_login"):
    process("%(HOME)s/.profile")
