#! /usr/bin/python

import re
import sys

assert not sys.stdin.isatty(), "stdin must be directed"
assert len(sys.argv) == 2, "Syntax: %s regexp" % sys.argv[0]

regexp = re.compile(sys.argv[1])
data = sys.stdin.read()
pos = 0

done = False
pos = 0
while not done:
  match = regexp.search(data[pos:])
  if match:
    start = pos + match.start(0)
    end = pos + match.end(0)
    print "%6d %s" % (start, repr(data[start if start < 20 else start-20:end+20]))
    pos = end
  else:
    done = True
