#! /usr/bin/python

import os
import sys
import time
import signal
import tempfile
import subprocess

def cleanup(signum=None, frame=None):
  signals = {1: "SIGHUP", 2: "SIGINT", 3: "SIGQUIT", 4: "SIGILL", 5: "SIGTRAP", 6: "SIGABRT", 6: "SIGIOT", 7: "SIGBUS", 8: "SIGFPE", 9: "SIGKILL", 10: "SIGUSR1", 11: "SIGSEGV", 12: "SIGUSR2", 13: "SIGPIPE", 14: "SIGALRM", 15: "SIGTERM", 16: "SIGSTKFLT", 17: "SIGCHLD", 18: "SIGCONT", 19: "SIGSTOP", 20: "SIGTSTP", 21: "SIGTTIN", 22: "SIGTTOU", 23: "SIGURG", 24: "SIGXCPU", 25: "SIGXFSZ", 26: "SIGVTALRM", 27: "SIGPROF", 28: "SIGWINCH", 29: "SIGIO", 29: "SIGLOST", 30: "SIGPWR", 31: "SIGSYS", 32: "SIGRTMIN", 8192: "SIGSTKSZ"}

  if signum:
    print "Caught signal %s" % (signals[signum] if signum in signals else signum)
  if name:
    print "Removing %s" % repr(name)
    os.remove(name)
  exit(0)

assert not sys.stdin.isatty(), "stdin must be redirected"

name = None

signal.signal(signal.SIGINT, cleanup)
signal.signal(signal.SIGTERM, cleanup)

(fd, name) = tempfile.mkstemp()
print "Created %s" % repr(name)
os.write(fd, sys.stdin.read())
os.close(fd)

with open("/dev/tty", 'r') as tty:
  p = subprocess.Popen(["vi", "-R", name], stdin=tty)
  rc = p.wait()

cleanup()
