#! /usr/bin/python

"""
  A better `comm` that doesn't expect the files to be sorted.
"""

def readFile(filename):
  with open(filename, 'r') as f:
    data = f.read()
    if data and data[-1] == '\n':
      data = data[:-1]
    return data.split('\n')

import sys
import getopt

skipUnique1 = False
skipUnique2 = False
skipCommon = False

(opts,args) = getopt.getopt(sys.argv[1:], "123", [])

for (opt,arg) in opts:
  if opt == '-1':
    skipUnique1 = not skipUnique1
  elif opt == '-2':
    skipUnique2 = not skipUnique2
  elif opt == '-3':
    skipCommon = not skipCommon
  else:
    raise Exception("Don't know how to handle %s" % repr(opt))

assert len(args) == 2, "Syntax: %s [-123] file1 file2" % sys.argv[0]

file1 = readFile(args[0])
file2 = readFile(args[1])

pos1 = 0
pos2 = 0

while (pos1 < len(file1)) or (pos2 < len(file2)):
  if (pos1 < len(file1)) and (pos2 < len(file2)) and (file1[pos1] == file2[pos2]):
    if not skipCommon:
      print file1[pos1]
    pos1 += 1
    pos2 += 1
  elif pos1 >= len(file1):
    if not skipUnique2:
      print '\t\t' + file2[pos2]
    pos2 += 1
  elif pos2 >= len(file2):
    if not skipUnique1:
      print '\t' + file1[pos1]
    pos1 += 1
  else:
    next1 = None
    next2 = None

    tmp = pos2 + 1
    while (tmp < len(file2)) and (not next2):
      if file1[pos1] == file2[tmp]:
        next2 = tmp
      else:
        tmp += 1

    tmp = pos1 + 1
    while (tmp < len(file1)) and (not next1):
      if file1[tmp] == file2[pos2]:
        next1 = tmp
      else:
        tmp += 1

    if (not next1) and (not next2):
      if not skipUnique1:
        print '\t' + file1[pos1]
      pos1 += 1
      if not skipUnique2:
        print '\t\t' + file2[pos2]
      pos2 += 1
    elif not next1:
      if not skipUnique1:
        print '\t' + file1[pos1]
      pos1 += 1
    elif not next2:
      if not skipUnique2:
        print '\t\t' + file2[pos2]
      pos2 += 1
    else:
      if next1 < next2:
        if not skipUnique1:
          print '\t' + file1[pos1]
        pos1 += 1
      else:
        if not skipUnique2:
          print '\t\t' + file2[pos2]
        pos2 += 1
