#! /usr/bin/python

import sys
import subprocess
import time
import getopt

def now():
  """
  Return current number of seconds since the epoch
  """
  return time.time()

def formatTime(secs=None):
  if secs == None:
    secs = now()
  return time.strftime("%Y-%m-%d %H:%M:%S.%s", time.localtime(secs))

arg = 1

negate = False
ignoreRC = False
(opts, args) = getopt.getopt(sys.argv[1:], "v", ["negate", "ignorerc"])

for (opt,arg) in opts:
  if opt in ["-v", "--negate"]:
    negate = not negate
  elif opt == "--ignorerc":
    ignoreRc = not ignoreRC

if len(args) < 2:
  sys.stderr.write("Syntax: %s -v string cmd ...\n" % sys.argv[0])
  exit(1)

string = args[0]
done = False
while not done:
  print formatTime()
  p = subprocess.Popen(args[1:], stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  stdout = p.stdout.read()
  stderr = p.stderr.read()
  rc = p.wait()
  sys.stdout.write(stdout)
  sys.stderr.write(stderr)
  print
  if (not ignoreRC) and (rc != 0):
    done = True
  elif (not negate) and (string not in stdout) and (string not in stderr):
    done = True
  elif negate and (string in stdout or string in stderr):
    done = True
  else:
    time.sleep(15)
