#! /usr/bin/python -u

import re
import sys
import math
import datetime

assert not sys.stdin.isatty(), "stdin must be redirected"

verbose = "--verbose" in sys.argv

"""
  Match for seconds or milliseconds (as an integer)
"""
regexp = re.compile("^(|.*\D)((\d{10}|\d{13})(\.\d+)?)([^0-9.].*|)$")

for line in sys.stdin:
  line = line.strip('\n')
  while True:
    match = regexp.search(line)
    if not match:
      break
    if verbose:
      sys.stderr.write("matched on %s\n" % match.group(2))
    secs = float(match.group(2))
    if int(math.log10(secs)+1) == 13:
      """
        If milliseconds have been expressed as an integer, convert it to seconds
      """
      secs /= 1000.0
    line = regexp.sub(str(datetime.datetime.fromtimestamp(secs)), line, count=1)

  print line
