#!/usr/bin/env python

import sys
import string
import os.path

def process(filename):
  tokens = [filename]
  basename = os.path.basename(filename)
  if basename not in [".", ".."]:
    tokens = basename.split('.')
  print "%s|%s" % (filename, "" if len(tokens) <= 1 else tokens[-1])

if len(sys.argv) == 1:
  if sys.stdin.isatty():
    sys.stderr.write("stdin is not redirected\n")
    exit(1)
  for line in sys.stdin:
    process(string.replace(string.replace(line, '\r', ''), '\n', ''))
else:
  for filename in sys.argv[1:]:
    process(filename)
