#! /usr/bin/python

import os
import sys
import base64
import getopt
import hashlib
import getpass
from cryptography.fernet import Fernet

assert not sys.stdin.isatty(), "stdin must be redirected"

encrypt = True

(opts,args) = ([], [])
try:
  (opts,args) = getopt.getopt(sys.argv[1:], "d", ["decrypt"])
except Exception as e:
  sys.stderr.write("Caught: %s\n" % e)
  exit(1)

for (opt,arg) in opts:
  if opt in ["-d", "--decrypt"]:
    encrypt = not encrypt
  
secret = getpass.getpass("Encryption key: ")

hash = hashlib.md5()
hash.update(secret)
fernet = Fernet(base64.b64encode(hash.hexdigest()))
  
data = sys.stdin.read()
if encrypt:
  result = fernet.encrypt(data)
else:
  result = fernet.decrypt(data)

sys.stdout.write(result)
