#! /usr/bin/python

import sys
import subprocess

def process(Filename):
  cmd = ["git", "log", filename]
  p = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  (stdout, stderr) = p.communicate()
  rc = p.wait()
  if (rc != 0) or (stderr):
    sys.stderr.write("%d from %s: %s\n" % (rc, cmd, repr(stderr)))
  else:
    print "%s %s" % ('+' if stdout else '-', filename)

for filename in sys.argv[1:]:
  process(filename)
