#! /usr/bin/python

import re
import sys
import json

assert not sys.stdin.isatty(), "sysin must be redirected"

objs = json.load(sys.stdin)

isInt = re.compile("^-?\d+$")

for elem in sys.argv[1:]:
  if isInt.search(elem):
    objs = objs[int(elem)]
  else:
    objs = objs[elem]

print json.dumps(objs, indent=2)
