#! /usr/bin/python

import re
import sys
import getopt
import importlib

(opts,args) = getopt.getopt(sys.argv[1:], "i:", ["import="])
for (opt,arg) in opts:
  if opt in ["-i", "--import"]:
    globals()[arg] = importlib.import_module(arg)

assert not sys.stdin.isatty(), "stdin must be directed"
assert len(args) == 2, "Syntax: %s [-i module1 -i module2 ... ] regexp expression"

regexp = re.compile(args[0])

for line in sys.stdin:
  line = line.strip('\n')
  match = regexp.search(line)
  if match:
    # print "Groups: %s" % str(match.groups())
    pos = len(match.groups())-1
    hit = match.groups()[pos]
    line = line[:match.start(pos)] + eval(args[1]) + line[match.end(pos):]
  print line
