#! /usr/bin/python

import re
import sys

assert not sys.stdin.isatty(), "stdin must be directed"
assert len(sys.argv) == 3, "Syntax: %s regexp expression"

regexp = re.compile(sys.argv[1])

for line in sys.stdin:
  line = line.strip('\n')
  match = regexp.search(line)
  if match:
    # print "Groups: %s" % str(match.groups())
    pos = len(match.groups())-1
    hit = match.groups()[pos]
    line = line[:match.start(pos)] + eval(sys.argv[2]) + line[match.end(pos):]
  print line
