#! /usr/bin/python

import getopt
import sys

assert not sys.stdin.isatty(), "stdin must be redirected"

sum = False
avg = False

(opts,args) = getopt.getopt(sys.argv[1:], "", ["sum", "total", "avg"])
for (opt,arg) in opts:
  if opt in ["--sum", "--total"]:
    sum = not sum
  elif opt == "--avg":
    avg = not avg

assert (int(sum) + int(avg)) == 1, "Select --avg or --sum/--total"
assert len(args) == 0, "Unexpected arguments: %s" % repr(args)

total = 0
count = 0
for line in sys.stdin:
  total += float(line)
  count += 1

if sum:
  print total
else:
  if count:
    print "%.2f" % (total/count)
