#! /usr/bin/python

import sys

assert not sys.stdin.isatty(), "stdin must be redirected"

assert len(sys.argv) == 3, "Syntax: %s 'from' 'to'" % sys.argv[0]

sys.stdout.write(sys.stdin.read().replace(eval(sys.argv[1]), eval(sys.argv[2])))
