#! /usr/bin/python

import sys
import hashlib
import os.path
import subprocess

def md5sum(filename):
  hasher = hashlib.md5()
  with open(filename, 'r') as f:
    hasher.update(f.read())
  return hasher.hexdigest()
    
for filename in sys.argv[1:]:
  if os.path.isfile(filename):
    comps = filename.split('/')
    # print "> %s" % comps
    comps.insert(-1, "safe")
    # print "> %s" % comps
    safeFilename = '/'.join(comps)
    # print "> %s" % safeFilename
    if os.path.isfile(safeFilename):
      sum = md5sum(filename)
      safeSum = md5sum(safeFilename)
      print "%s %s" % (sum, filename)
      print "%s %s" % (safeSum, safeFilename)
      if sum == safeSum:
          p = subprocess.Popen(["mv", "-v", safeFilename, filename])
          rc = p.wait()
      print ""
    else:
      sys.stderr.write("Not a file: `%s`\n" % safeFilename)
  else:
    sys.stderr.write("Not a file: `%s`\n" % filename)
