#! /usr/bin/python

import sys
import os.path
import datetime

def process(filename):
  if os.path.exists(filename):
    if os.path.isfile(filename):
        files[filename] = datetime.datetime.strftime(datetime.datetime.fromtimestamp(os.path.getmtime(filename)), "%Y/%m/%d %H:%M:%S.%f")
    else:
      sys.stderr.write("`%s` is not a regular file\n" % filename)
  else:
    sys.stderr.write("`%s` does not exist\n" % filename)


files = {}
if len(sys.argv) > 1:
  for filename in sys.argv[1:]:
    process(filename)
else:
  assert not sys.stdin.isatty(), "stdin must be redirected or you must specify files as arguments"
  for filename in sys.stdin.read().strip('\n').split('\n'):
    process(filename)

for filename in sorted(files, key=lambda file: files[file], reverse=True):
  print "%s %s" % (files[filename], filename)
