#! /usr/bin/python

import re
import os
import os.path
import pwd
import sys

"""
>>> pwd.getpwuid(os.getuid())
pwd.struct_passwd(pw_name='ibmadmin', pw_passwd='x', pw_uid=1000, pw_gid=1000, pw_gecos='ibmadmin,,,', pw_dir='/home/ibmadmin', pw_shell='/bin/bash')
>>> os.uname()
('Linux', 'pfuntner-dev-0', '4.4.0-78-generic', '#99-Ubuntu SMP Thu Apr 27 15:29:09 UTC 2017', 'x86_64')
>>>
"""

nodeAliases = {"pfuntner-dev-0": "pfuntner-dev"}

user = pwd.getpwuid(os.getuid()).pw_name

node = os.uname()[1]

# import pdb; pdb.set_trace()

# print "node is %s" % repr(node)
if node in nodeAliases:
  # print "%s is in nodeAliases" % repr(node)
  node = nodeAliases[node]
  # print "node is %s" % repr(node)

cwd = os.getcwd()

regexp = re.compile("/")

for filename in sys.argv[1:]:
  print "%s@%s:%s" % (user, node, filename if regexp.match(filename) else os.path.join(cwd, filename))
