#! /usr/bin/env python3

import signal
import socket
import logging
import argparse
import subprocess

def run(cmd, stdin=None, capture=True, shell=False):
  if shell:
    if isinstance(cmd, list):
      cmd = ' '.join(cmd)
  elif isinstance(cmd, str):
    cmd = cmd.split()

  log.info('Executing {cmd}'.format(**locals()))
  p = subprocess.Popen(cmd, stdin=subprocess.PIPE if stdin else None, stdout=subprocess.PIPE if capture else None, stderr=subprocess.PIPE if capture else None, shell=shell)
  if stdin:
    p.stdin.write(stdin.encode())
    p.stdin.close()
  if capture:
    (stdout, stderr) = tuple([s.decode('utf-8') for s in p.communicate()])
    # alternately, if trapping is conditional:
    # if trap:
    #   stdout = stdout.decode('utf-8')
    #   stderr = stderr.decode('utf-8')
  else:
    (stdout, stderr) = ('', '')
  rc = p.wait()
  log.debug('Executed {cmd}: {rc}, {stdout!r}, {stderr!r}'.format(**locals()))
  return (rc, stdout, stderr)

parser = argparse.ArgumentParser(description='Discover bruno-meerkat ip')
parser.add_argument('-v', '--verbose', action='count', help='Enable debugging')
args = parser.parse_args()

logging.basicConfig(format='%(asctime)s %(levelname)s %(pathname)s:%(lineno)d %(msg)s')
log = logging.getLogger()
# log.setLevel(logging.DEBUG if args.verbose else logging.WARNING)
log.setLevel(logging.WARNING - (args.verbose or 0)*10)

signal.signal(signal.SIGPIPE, lambda signum, stack_frame: exit(0))

"""
[John Pfuntner@BrunoDellLaptop ~]$ for ip in 192.168.1.{1..16}; do ssh -o ConnectTimeout=1 mrbruno@$ip hostname; done
ssh: connect to host 192.168.1.1 port 22: Connection timed out
ssh: connect to host 192.168.1.2 port 22: Connection timed out
ssh: connect to host 192.168.1.3 port 22: Connection timed out
ssh: connect to host 192.168.1.4 port 22: Connection timed out
ssh: connect to host 192.168.1.5 port 22: Connection timed out
ssh: connect to host 192.168.1.6 port 22: Connection timed out
ssh: connect to host 192.168.1.7 port 22: Connection timed out
ssh: connect to host 192.168.1.8 port 22: Connection timed out
ssh: connect to host 192.168.1.9 port 22: Connection timed out
ssh: connect to host 192.168.1.10 port 22: Connection timed out
bruno-meerkat
ssh: connect to host 192.168.1.12 port 22: Connection timed out
ssh: connect to host 192.168.1.13 port 22: Connection timed out
ssh: connect to host 192.168.1.14 port 22: Connection timed out
ssh: connect to host 192.168.1.15 port 22: Connection timed out
ssh: connect to host 192.168.1.16 port 22: Connection timed out
[John Pfuntner@BrunoDellLaptop ~]$ ifconfig
-bash: ifconfig: command not found
[John Pfuntner@BrunoDellLaptop ~]$ ipconfig

Windows IP Configuration


Wireless LAN adapter Local Area Connection* 1:

   Media State . . . . . . . . . . . : Media disconnected
   Connection-specific DNS Suffix  . :

Wireless LAN adapter Local Area Connection* 2:

   Media State . . . . . . . . . . . : Media disconnected
   Connection-specific DNS Suffix  . :

Wireless LAN adapter Wi-Fi:

   Connection-specific DNS Suffix  . :
   Link-local IPv6 Address . . . . . : fe80::297d:831f:1435:198b%20
   IPv4 Address. . . . . . . . . . . : 192.168.1.9
   Subnet Mask . . . . . . . . . . . : 255.255.255.0
   Default Gateway . . . . . . . . . : 192.168.1.1
[John Pfuntner@BrunoDellLaptop ~]$ whatami
It is Sat 2020-11-14 19:46:17.520277 UTC
I am /home/John Pfuntner/bin/whatami: 2019-12-21 17:49:30, github.com:pfuntner/toys, master, a33a23, e78e515955f43f091dc86aca9aaa19b7

['uname', '-a']: 'CYGWIN_NT-10.0 BrunoDellLaptop 3.1.4(0.340/5/3) 2020-02-19 08:49 x86_64 Cygwin'
['uname', '-n']: 'BrunoDellLaptop'
['uname', '-s']: 'CYGWIN_NT-10.0'
['uname', '-v']: '2020-02-19 08:49'
['uname', '-r']: '3.1.4(0.340/5/3)'
['uname', '-m']: 'x86_64'
['uname', '-p']: 'unknown'
['uname', '-i']: 'unknown'
['uname', '-o']: 'Cygwin'

sys.version: ['3.6.9 (default, Jul 21 2019, 14:33:59) ', '[GCC 7.4.0]']
sys.platform: 'cygwin'
sys.path: ['/home/John Pfuntner/repos/toys/bin', '/usr/lib/python36.zip', '/usr/lib/python3.6', '/usr/lib/python3.6/lib-dynload', '/usr/lib/python3.6/site-packages']

socket.gethostname(): 'BrunoDellLaptop'
socket.gethostbyname(socket.gethostname()): '192.168.1.9'
socket.gethostbyname_ex(socket.gethostname()): ('BrunoDellLaptop', [], ['192.168.1.9'])
ipconfig: 192.168.1.9 (Wireless LAN adapter Wi-Fi)

Free RAM: 565MB/4GB 13.81%
CPU name: AMD A9-9420e RADEON R5, 5 COMPUTE CORES 2C+3G
"""

my_ip = socket.gethostbyname(socket.gethostname())
log.info(f'my_ip: {my_ip}')

nybbles = my_ip.split('.')
for nybble in range(1,17):
  ip = '.'.join(nybbles[:3] + [str(nybble)])
  if ip != my_ip:
    log.info(f'Testing {ip!r}...')
    (rc, stdout, stderr) = run(f'ssh -o ConnectTimeout=1 mrbruno@{ip} exit 42')
    if rc == 42:
      print(ip)
      exit(0)

log.warn('Could not find meerkat system')
